export SETUP_PING=1.1.1.1               # IP address or domain name for testing network connectivity
# SETUP_DISK=/dev/vda              # The disk to install Arch Linux on (unset by default, an unmounted disk is automatically selected)
export SETUP_DISK_MIN_BYTES=16000000000 # The minimum number of bytes that a disk must have to be automatically selected for installation (default 16 GB)
export SETUP_HEADLESS=false             # Whether to install a display server and other related software
export SETUP_DEVELOPMENT_TOOLS=true     # Whether to install development tools
export SETUP_EXTRA_PACKAGES=""          # Extra packages to install on the system
export SETUP_TIME_ZONE=America/Denver   # The system time zone
export SETUP_HOSTNAME="arch"            # The system hostname
export SETUP_ROOT_PASSWORD="arch"       # The root password
export SETUP_USER="main"                # The name of the non-root account
export SETUP_USER_PASSWORD="main"       # The password for the non-root account
export SETUP_SUDO_GROUP="wheel"         # The name of the group with sudo privileges
export SETUP_SSH_PORT=22                # The port for ssh to listen on
export SETUP_RESTART_TIME=5             # The timed delay before restarting once installation is complete (-1 cancels the restart)
